---

- name: "Look up entry in passwd for user {{ pulp_user }}"
  become: true
  ansible.builtin.getent:
    database: passwd
    key: "{{ pulp_user }}"

- name: Set pulp user uid
  ansible.builtin.set_fact:
    pulp_uid: "{{ ansible_facts.getent_passwd[pulp_user][1] }}"

- name: List user services
  become: true
  become_user: "{{ pulp_user }}"
  environment:
    XDG_RUNTIME_DIR: "/run/user/{{ pulp_uid }}"
  ansible.builtin.command:
    cmd: >
      systemctl --user list-units
      --type=service
      --all
      --no-pager
      --output=json
  register: user_services
  changed_when: false

- name: Extract unit names
  ansible.builtin.set_fact:
    service_names: "{{ user_services.stdout | from_json | map(attribute='unit') | list }}"

- name: Stop pulp service
  become: true
  become_user: "{{ pulp_user }}"
  when: pulp_container_name ~ '.service' in service_names
  ansible.builtin.systemd_service:
    name: "{{ pulp_container_name }}.service"
    enabled: false
    state: stopped
    scope: user

- name: Remove rootless user setup
  become: true
  ansible.builtin.import_role:
    name: philnewm.podman_rootless_user
  vars:
    state: "{{ state }}"

...
