---

- name: Include rootless user setup
  become: true
  ansible.builtin.import_role:
    name: philnewm.podman_rootless_user
  vars:
    rootless_user: "{{ pulp_user }}"
    rootless_user_home: "/var/lib/{{ pulp_user }}"
    system_user: true

- name: Ensure required podman packages are installed
  become: true
  ansible.builtin.package:
    name: "{{ podman_packages }}"
    state: present
    update_cache: true

- name: Include pulp setup
  ansible.builtin.include_tasks:
    file: service_setup.yml

- name: Gather service facts
  ansible.builtin.service_facts:

- name: Open required firewall ports
  become: true
  loop: "{{ pulp_firewall_ports | default([]) }}"
  loop_control:
    loop_var: pulp_firewall_port
  when: "'firewalld' in ansible_facts.services"
  ansible.posix.firewalld:
    port: "{{ pulp_firewall_port }}"
    state: "enabled"
    permanent: true
    immediate: true

- name: Set up pulp-cli for pulp squeezer and manual usage
  when: pulp_cli
  ansible.builtin.include_tasks:
    file: "pulp_venv.yml"

- name: Include pulp rpm config
  when: pulp_rpm_remotes is defined or pulp_rpm_repositories is defined
  ansible.builtin.include_tasks:
    file: rpm_config.yml

- name: Include pulp python config
  when: pulp_python_remotes is defined or pulp_python_repositories is defined
  ansible.builtin.include_tasks:
    file: python_config.yml

- name: Include pulp python config
  when: pulp_file_repositories is defined or pulp_file_content is defined
  ansible.builtin.include_tasks:
    file: file_config.yml

- name: Include pulp ansible config
  when: pulp_ansible_repositories is defined or pulp_ansible_collections_remotes is defined or pulp_ansible_roles_remotes is defined
  ansible.builtin.include_tasks:
    file: ansible_config.yml

- name: Include pulp ansible config
  when: pulp_container_remotes is defined or pulp_container_repositories is defined
  ansible.builtin.include_tasks:
    file: container_config.yml

...
