---

- name: Create rpm remotes
  environment:
    PYTHONPATH: "{{ pulp_ansible_venv }}/lib/python{{ ansible_facts.python.version.major }}.{{ ansible_facts.python.version.minor }}/site-packages"
  loop: "{{ pulp_rpm_remotes }}"
  loop_control:
    loop_var: rpm_remote
    label: "{{ rpm_remote.name }}"
  pulp.squeezer.rpm_remote:
    pulp_url: "{{ pulp_url }}"
    username: "{{ pulp_admin_username }}"
    password: "{{ pulp_admin_password }}"
    name: "{{ rpm_remote.name }}"
    url: "{{ rpm_remote.url }}"
    policy: "{{ rpm_remote.policy }}"
    state: present

- name: Create rpm repositories
  environment:
    PYTHONPATH: "{{ pulp_ansible_venv }}/lib/python{{ ansible_facts.python.version.major }}.{{ ansible_facts.python.version.minor }}/site-packages"
  loop: "{{ pulp_rpm_repositories }}"
  loop_control:
    loop_var: rpm_repository
    label: "{{ rpm_repository.name }}"
  pulp.squeezer.rpm_repository:
    pulp_url: "{{ pulp_url }}"
    username: "{{ pulp_admin_username }}"
    password: "{{ pulp_admin_password }}"
    name: "{{ rpm_repository.name }}"
    description: "{{ rpm_repository.description }}"
    autopublish: "{{ rpm_repository.autopublish }}"
    repo_config: "{{ rpm_repository.repo_config | default(omit) }}"
    remote: "{{ rpm_repository.remote }}"
    retain_package_versions: "{{ rpm_repository.retain_package_versions }}"
    pulp_labels: "{{ rpm_repository.pulp_labels | default(omit) }}"
    state: present

...
