---

- name: Read /etc/subuid
  ansible.builtin.shell:
    cmd: |
      set -o pipefail
      cat /etc/subuid | grep {{ pulp_user }}
    executable: /bin/bash
  register: subuids
  changed_when: false

- name: Read /etc/subgid
  ansible.builtin.shell:
    cmd: |
      set -o pipefail
      cat /etc/subgid | grep {{ pulp_user }}
    executable: /bin/bash
  register: subgids
  changed_when: false

- name: Ensure directories for volumes exist
  become: true
  loop: "{{ pulp_volumes }}"
  loop_control:
    label: "{{ item.name }}"
  ansible.builtin.file:
    path: "{{ item.host_path }}"
    state: directory
    owner: "{{ item.owner | default(pulp_user) }}"
    group: "{{ item.group | default(pulp_user) }}"
    mode: "{{ item.permissions }}"

- name: Ensure certs directories exist
  become: true
  ansible.builtin.file:
    path: "{{ pulp_service_dir }}/settings/certs"
    state: directory
    owner: "{{ pulp_user }}"
    group: "{{ pulp_user }}"
    mode: '0755'

- name: Ensure pulp content_origin is set
  become: true
  become_user: "{{ pulp_user }}"
  loop:
    - "CONTENT_ORIGIN='http://{{ ansible_facts.hostname }}:8080'"
    - "CONTENT_PATH_PREFIX='{{ pulp_content_path_prefix }}'"
  ansible.builtin.lineinfile:
    path: "{{ pulp_service_dir }}/settings/settings.py"
    line: "{{ item }}"
    create: true
    state: present
    mode: '0644'

- name: Ensure .config/systemd/user directory exists
  become: true
  ansible.builtin.file:
    path: "{{ pulp_user_home }}/.config/containers/systemd"
    state: directory
    owner: "{{ pulp_user }}"
    group: "{{ pulp_user }}"
    mode: "0700"

- name: Generate list of volume mappings
  ansible.builtin.set_fact:
    pulp_volumes_mounts: >-
      {{ pulp_volumes
        | map(attribute='host_path')
        | zip(pulp_volumes | map(attribute='container_path'))
        | map('join', ':')
        | list }}

- name: Check for selinux mode
  ansible.builtin.command:
    cmd: getenforce
  failed_when: false
  changed_when: false
  register: se_linux_status

- name: Add :z suffix if SELinux enforcing
  when: se_linux_status.stdout | lower == 'enforcing'
  ansible.builtin.set_fact:
    pulp_volumes_mounts: "{{ pulp_volumes_mounts | product([':Z']) | map('join', '') | list }}"

- name: "Look up entry in passwd for user {{ pulp_user }}"
  become: true
  ansible.builtin.getent:
    database: passwd
    key: "{{ pulp_user }}"

- name: Set pulp user uid
  ansible.builtin.set_fact:
    pulp_uid: "{{ ansible_facts.getent_passwd[pulp_user][1] }}"

- name: Template pulp quadlet
  become: true
  ansible.builtin.template:
    src: pulp.container.j2
    dest: "{{ pulp_user_home }}/.config/containers/systemd/pulp.container"
    owner: "{{ pulp_user }}"
    group: "{{ pulp_user }}"
    mode: "0640"

# Note /var/run/user/<uid>/systemd/generator/pulp.service
- name: Enable and start generated systemd service
  become: true
  become_user: "{{ pulp_user }}"
  ansible.builtin.systemd:
    name: "{{ pulp_container_name }}.service"
    scope: user
    enabled: true
    state: started
    daemon_reload: true
  register: pulp_service_result

- name: Wait for Pulp API to be ready
  ansible.builtin.uri:
    url: "{{ pulp_url }}/pulp/api/v3/status/"
  register: pulp_status_endpoint_post_install
  retries: 120
  delay: 3
  until: pulp_status_endpoint_post_install.status == 200

- name: Set admin password inside pulp container
  become: true
  become_user: "{{ pulp_user }}"
  when: pulp_service_result.changed # noqa: no-handler
  containers.podman.podman_container_exec:
    name: pulp
    command: >
      pulpcore-manager reset-admin-password --password '{{ pulp_admin_password }}'

...
