---

- name: Install pulp.squeezer dependencies into venv
  become: true
  ansible.builtin.pip:
    name: "{{ pulp_venv_python_packages }}"
    virtualenv: "{{ pulp_ansible_venv }}"
    virtualenv_command: "python3 -m venv"

- name: Check for selinux mode
  when: ansible_os_family == "RedHat"
  ansible.builtin.command:
    cmd: getenforce
  changed_when: false
  register: se_linux_status

- name: Ensure directories for volumes exist
  become: true
  become_user: "{{ pulp_user }}"
  loop: "{{ pulp_volumes }}"
  loop_control:
    label: "{{ item.name }}"
  ansible.builtin.file:
    path: "{{ item.host_path }}"
    state: directory
    mode: "{{ item.permissions }}"

- name: Ensure certs directories exist
  become: true
  become_user: "{{ pulp_user }}"
  ansible.builtin.file:
    path: "{{ pulp_user_home }}/pulp/settings/certs"
    state: directory
    mode: '0755'

- name: Ensure pulp content_origin is set
  become: true
  become_user: "{{ pulp_user }}"
  loop:
    - "CONTENT_ORIGIN='http://{{ ansible_hostname }}:8080'"
    - "CONTENT_PATH_PREFIX='{{ pulp_content_path_prefix }}'"
  ansible.builtin.lineinfile:
    path: "{{ pulp_user_home }}/pulp/settings/settings.py"
    line: "{{ item }}"
    create: true
    state: present
    mode: '0644'

- name: Ensure .config/systemd/user directory exists
  become: true
  ansible.builtin.file:
    path: "{{ pulp_user_home }}/.config/containers/systemd"
    state: directory
    owner: "{{ pulp_user }}"
    group: "{{ pulp_user }}"
    mode: "0700"

# TODO more elegant solution
- name: Prepare volume mounts with SELinux relabel if needed
  ansible.builtin.set_fact:
    pulp_volumes_mounts: >-
      {{
        pulp_volumes
        | map('community.general.json_query',
              "join(':', [host_path, container_path])")
        | map('regex_replace', '$',
              ':Z' if (se_linux_status.stdout | default('disabled') | lower) == 'enforcing' else '')
        | list
      }}

# - name: Show combined volumes
#   ansible.builtin.debug:
#     msg: "{{ pulp_volumes_mounts }}"

- name: Create pulp container with podman
  become: true
  become_user: "{{ pulp_user }}"
  containers.podman.podman_container:
    name: "{{ pulp_container_name }}"
    image: "{{ pulp_image }}"
    publish: "{{ pulp_ports }}"
    detach: false  # INFO to get logs in journald
    device: "/dev/fuse"
    privileged: false
    tty: false
    network: "slirp4netns"
    pull: "missing"
    log_driver: "journald"
    volume: "{{ pulp_volumes_mounts }}"
    state: "quadlet"
    quadlet_dir: "{{ pulp_user_home }}/.config/containers/systemd"
    quadlet_file_mode: "0640"
    quadlet_filename: "{{ pulp_container_name }}.container"
    quadlet_options:
      - "AutoUpdate=registry"
      - "Pull=newer"
      - |
        [Install]
        WantedBy=default.target
      - |
        [Unit]
        Description=Podman container pulp.service
        Wants=network-online.target
        After=network-online.target
        RequiresMountsFor=/run/user/{{ pulp_uid }}/containers
      - |
        [Service]
        Restart=always
        RestartSec=10
        TimeoutStopSec=180

# INFO /var/run/user/<uid>/systemd/generator/pulp.service
- name: Enable and start generated systemd service
  become: true
  become_user: "{{ pulp_user }}"
  ansible.builtin.systemd:
    name: "{{ pulp_container_name }}.service"
    scope: user
    enabled: true
    state: started
    daemon_reload: true

...
